# Generated by Django 5.1.4 on 2025-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField()),
                ('total_tickets', models.IntegerField()),
                ('winners', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('numbers', models.CharField(max_length=20)),
                ('is_auto', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField(auto_now_add=True)),
                ('numbers', models.CharField(max_length=20)),
            ],
        ),
    ]
